name: Build and Restore

on:
  push:
    branches:
      - main  # ajusta esto según tu rama principal

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Restore NuGet Packages
      run: |
        cd D:\a\webex\webex
        nuget restore
